export const ProdActionTypes = {
    ADD_PROD_START:'ADD_PROD_START',
    ADD_PROD_SUCCESS:'ADD_PROD_SUCCESS',
    ADD_PROD_FAILURE:'ADD_PROD_FAILURE',

    EDIT_PROD_START:'EDIT_PROD_START',
    EDIT_PROD_SUCCESS:'EDIT_PROD_SUCCESS',
    EDIT_PROD_FAILURE:'EDIT_PROD_FAILURE',

    DELETE_PROD_START:'DELETE_PROD_START',
    DELETE_PROD_SUCCESS:'DELETE_PROD_SUCCESS',
    DELETE_PROD_FAILURE:'DELETE_PROD_FAILURE',

    GET_PROD_START:'GET_PROD_START',
    GET_PROD_SUCCESS:'GET_PROD_SUCCESS',
    GET_PROD_FAILURE:'GET_PROD_FAILURE',

    FETCH_COLLECTIONS_START_PROD:'FETCH_COLLECTIONS_START_PROD',
    FETCH_COLLECTIONS_SUCCESS_PROD:'FETCH_COLLECTIONS_SUCCESS_PROD',
    FETCH_COLLECTIONS_FAILURE_PROD:'FETCH_COLLECTIONS_FAILURE_PROD',
}
